import Head from "next/head";
import Header from "@/components/Header";
import Hero from "@/components/Hero";
import Deal from "@/components/Deal";
import HowDoesWork from "@/components/HowDoesWork";
import PopularItemSlider from "@/components/PopularItemSlider";
import FeaturedRestaurants from "@/components/FeaturedRestaurants";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <Hero />
            <Deal />
            <HowDoesWork />
            <PopularItemSlider />
            <FeaturedRestaurants />
        </>
    );
}
